@echo off
color 1f
echo Aguardando a permisao...
echo Se for recusada o programa fechara!
echo Carregando...
ping localhost -n 2 > nul
setlocal DisableDelayedExpansion
set "batchPath=%~0"
for %%k in (%0) do set batchName=%%~nk
set "vbsGetPrivileges=%temp%\OEgetPriv_%batchName%.vbs"
setlocal EnableDelayedExpansion

:checkPrivileges
NET FILE 1>NUL 2>NUL
if '%errorlevel%' == '0' ( goto gotPrivileges ) else ( goto getPrivileges )

:getPrivileges
if '%1'=='ELEV' (echo ELEV & shift /1 & goto gotPrivileges)
echo Set UAC = CreateObject^("Shell.Application"^) > "%vbsGetPrivileges%"
echo args = "ELEV " >> "%vbsGetPrivileges%"
echo For Each strArg in WScript.Arguments >> "%vbsGetPrivileges%"
echo args = args ^& strArg ^& " "  >> "%vbsGetPrivileges%"
echo Next >> "%vbsGetPrivileges%"
echo UAC.ShellExecute "!batchPath!", args, "", "runas", 1 >> "%vbsGetPrivileges%"
"%SystemRoot%\System32\WScript.exe" "%vbsGetPrivileges%" %*
exit /B

:gotPrivileges
setlocal & pushd .
cd /d %~dp0
if '%1'=='ELEV' (del "%vbsGetPrivileges%" 1>nul 2>nul  &  shift /1)
goto update

:update
color 1f
title Atualizador do LENDASDOCAMINHARpxm
cls
echo ======================================
echo Atualizador do LENDASDOCAMINHARpxm
echo ++++++++++++++++++++++++++++++++++++++
echo Deseja atualizar?
echo Deve estar fechado o Minecraft.
echo Durante a instalacao nao feche a janela
echo --------------------------------------
echo Recursos que o atualizador vai instalar,
echo caso ja tenha ele vai so passar:
echo 1) Chocolatey
echo 2) Git
echo 3) Do LENDASDOCAMINHARpxm instalado
echo --------------------------------------
echo Sinais do processo:
echo [-] Nulo [+] Atual [X] Feito [v] Atualizado [!] Erro.
echo S para sim ou N para nao.
choice
if %errorlevel% equ 1 goto 1
if %errorlevel% equ 2 goto exit
if %errorlevel% equ 0 goto exit
goto update

:1
cls
color 1f
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [+] Fechando o minecraft caso ele esteja aberto.
echo [-] Verificacao/baixando programas...
echo [-] Verificando atualizacoes...
echo [-] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 1/10.
echo --------------------------------------
echo Fechando tafera...
taskkill /f /im java.exe
taskkill /f /im javaw.exe
goto 2

:2
cls
color 1f
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [+] Verificacao/baixando programas...
echo [-] Verificando atualizacoes...
echo [-] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 2/10.
echo --------------------------------------
echo Verificando LENDASDOCAMINHARpxm...
ping localhost -n 3 > nul
if not exist "%appdata%\.minecraft\versions\LENDASDOCAMINHARpxm\atualizador" goto errornooixe
echo Baixando Chocolatey...
powershell Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
echo Confirmando a instalacao...
color 1f
ping localhost -n 10 > nul
echo Baixando/Atualizando Git...
choco install git
echo Aguardando aprovacao...
ping localhost -n 4 > nul
if exist "%systemdrive%\Program Files\Git" goto 3
if exist "%systemdrive%\Program Files (x86)\Git" goto 3
if exist "%systemdrive%\ProgramData\Microsoft\Windows\Start Menu\Programs\Git" goto 3
cls
color cf
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [!] Verificacao/baixando programas...
echo [-] Verificando atualizacoes...
echo [-] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 2/10. Erro!
echo --------------------------------------
echo Nao foi possivel baixar o Git.
echo Caso queira cancelar feche a janela.
echo Tentando novamente em...
timeout /t 10
goto 2

:errornooixe
cls
color cf
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [!] Verificacao/baixando programas...
echo [-] Verificando atualizacoes...
echo [-] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 2/10. Erro!
echo --------------------------------------
echo Verificando LENDASDOCAMINHARpxm...
echo Nao tem instalado o instalador do LENDASDOCAMINHARpxm.
echo Caso queira cancelar feche.
echo Tentando de novo em...
timeout /t 10
goto 2

:3
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [+] Verificando atualizacoes...
echo [-] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 3/10.
echo --------------------------------------
echo Essa parte baixa o verificador de
echo atualizacoes do LENDASDOCAMINHARpxm.
cd /
%systemdrive%
cd "%appdata%\.minecraft\versions\LENDASDOCAMINHARpxm"
cd versao
git clone https://github.com/ayrigom/PIXELGUTOV3-update-verification.git
cd PIXELGUTOV3-update-verification
if not exist "v1.txt" goto 4
color 2f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [v] Verificando atualizacoes...
echo [-] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 3/10.
echo --------------------------------------
cd ..
echo Ja esta atualizado.
echo Pode fechar, mas caso queira re-passar
echo Precione qualquer tecla tres vezes para re-passar. . .
pause > nul
pause > nul
pause > nul
goto 4

:4
color 1f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [+] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 4/10.
echo --------------------------------------
echo Parte nescessaria pois pode ter
echo mudancas nos codigo da instalacao.
echo AVISO! apos esta atualizacao nao podera fechar a tela,
echo pois causara problema com a versao da atualizacao,
echo tera que vir outra atualizacao para resolver!
timeout /t 30
color 1f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [+] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 4/10.
echo --------------------------------------
echo Atualizando atualizador...
echo Essa parte ele pode fazer alguns
echo codigos diferente.
ping localhost -n 4 > nul
copy /y "atualizar.bat" "%appdata%\.minecraft\versions\LENDASDOCAMINHARpxm\atualizador"
ping localhost -n 3 > nul
if exist "novo.txt" goto novo
echo Sem codigos novos nescessario, atualizador atualizado/progredido!
echo Continue sem fechar.
timout /t 10
goto 5

:novo
color 1f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [+] Baixando o atualizador atualizado...
echo [-] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 4/10.
echo --------------------------------------
echo Tem mudancas no codigos.
echo Fazendo alteracoes...
goto 5

:5
color 1f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [X] Baixando o atualizador atualizado...
echo [+] Vendo se precisa adicionar um arquivo novo...
echo [-] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 5/10.
echo --------------------------------------
rd /s /q PIXELGUTOV3-update-verification > nul
cd ..
rd /s /q PIXELGUTOV3-update-verification > nul
echo Parte nao nescessaria, nao a mudancas nescessaria.
timeout /t 10
goto 6

:6
color 1f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [X] Baixando o atualizador atualizado...
echo [X] Vendo se precisa adicionar um arquivo novo...
echo [+] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 6/10.
echo --------------------------------------
echo Baixando...
cd "%appdata%\.minecraft\versions\LENDASDOCAMINHARpxm\baixados"
git clone https://github.com/ayrigom/PIXELGUTOV3-update.git
if not exist PIXELGUTOV3-update goto errornodown
cd PIXELGUTOV3-update
goto 7

:errornodown
color cf
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [X] Baixando o atualizador atualizado...
echo [X] Vendo se precisa adicionar um arquivo novo...
echo [!] Baixando atualizacao...
echo [-] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 6/10. Erro!
echo --------------------------------------
echo Nao foi possivel baixar a atualizacao.
echo Caso queira cancelar feche antes de...
timeout /t 10
goto 6


:7
color 1f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [X] Baixando o atualizador atualizado...
echo [X] Vendo se precisa adicionar um arquivo novo...
echo [X] Baixando atualizacao...
echo [+] Atualizando...
echo [-] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 7/10.
echo --------------------------------------
echo Atualizando...
echo Copiando arquivos/mods...
ping localhost -n 4 > nul
copy /y "*.jar" "%appdata%\.minecraft\versions\LENDASDOCAMINHARpxm\mods"
goto 8

:8
color 1f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [X] Baixando o atualizador atualizado...
echo [X] Vendo se precisa adicionar um arquivo novo...
echo [X] Baixando atualizacao...
echo [X] Atualizando...
echo [+] Verificando se atualizou...
echo [-] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 8/10.
echo --------------------------------------
echo Arquivos passados!
ping localhost -n 4 > nul
goto 9

:9
color 1f
cls
echo ======================================
echo            Atualizando...
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [X] Baixando o atualizador atualizado...
echo [X] Vendo se precisa adicionar um arquivo novo...
echo [X] Baixando atualizacao...
echo [X] Atualizando...
echo [X] Verificando se atualizou...
echo [+] Removendo arquivos baixados...
echo [-] Concluido.
echo --------------------------------------
echo Progresso 9/10.
echo --------------------------------------
echo Removendo arquivos baixados...
cd ..
rd /s /q "PIXELGUTOV3-update"
ping localhost -n 5 > nul
goto 10

:10
color 2f
cls
echo ======================================
echo             Atualizado!
echo ++++++++++++++++++++++++++++++++++++++
echo [X] Fechando o minecraft caso ele esteja aberto.
echo [X] Verificacao/baixando programas...
echo [X] Verificando atualizacoes...
echo [X] Baixando o atualizador atualizado...
echo [X] Vendo se precisa adicionar um arquivo novo...
echo [X] Baixando atualizacao...
echo [X] Atualizando...
echo [X] Verificando se atualizou...
echo [X] Removendo arquivos baixados...
echo [X] Concluido.
echo --------------------------------------
echo Progresso 10/10. Concluido!
echo --------------------------------------
echo Tudo certo!
echo Precione qualquer tecla para sair. . .
pause > nul
goto exit

:exit
cls
echo Fechando...
ping localhost -n 3 > nul
color 0f
